spring.application.name=MarchMadness
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

# AWS PostgreSQL configuration.
aws.psql.enabled=${AWS_PSQL_ENABLED:false}
aws.psql.host=${AWS_PSQL_HOST:}
aws.psql.port=${AWS_PSQL_PORT:5432}
aws.psql.database=${AWS_PSQL_DATABASE:}
aws.psql.username=${AWS_PSQL_USERNAME:}
aws.psql.password=${AWS_PSQL_PASSWORD:}
